services:
  parser-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - parser_app_data:/data
    restart: unless-stopped

volumes:
  parser_app_data:
