from ..v1.history_report import CancellationRequested, VehicleHistoryClient
from ..v1.otomoto_vehicle_identity import fetch_otomoto_listing_page_data, fetch_otomoto_vehicle_identity
from ._service_analysis import ServiceAnalysisMixin
from ._service_analysis_helpers import default_red_flag_analyzer
from ._service_categories import ServiceCategoryMixin
from ._service_common import (
    ANALYSIS_PROGRESS_CALLING_MODEL,
    ANALYSIS_PROGRESS_COLLECTING_DATA,
    ANALYSIS_STATUS_CANCELLED,
    ANALYSIS_STATUS_CANCELLING,
    ANALYSIS_STATUS_FAILED,
    ANALYSIS_STATUS_IDLE,
    ANALYSIS_STATUS_RUNNING,
    ANALYSIS_STATUS_SUCCESS,
    ASSIGNABLE_CATEGORY_ORDER,
    CATEGORY_DATA_NOT_VERIFIED,
    CATEGORY_FAVORITES,
    CATEGORY_IMPORTED_FROM_US,
    CATEGORY_PRICE_OUT_OF_RANGE,
    CATEGORY_TO_BE_CHECKED,
    CUSTOM_CATEGORY_PREFIX,
    DEFAULT_REPORT_LOOKUP_DAYS_BACK,
    DEFAULT_REPORT_LOOKUP_DAYS_FORWARD,
    OPENAI_REDFLAG_MODEL,
    OPENAI_RESPONSES_URL,
    REPORT_MISSING_FIRST_REGISTRATION,
    REPORT_MISSING_REGISTRATION,
    REPORT_MISSING_REGISTRATION_AND_DATE,
    REPORT_PROGRESS_FETCHING_IDENTITY,
    REPORT_PROGRESS_FETCHING_REPORT,
    REPORT_STATUS_CANCELLED,
    REPORT_STATUS_CANCELLING,
    REPORT_STATUS_FAILED,
    REPORT_STATUS_IDLE,
    REPORT_STATUS_NEEDS_INPUT,
    REPORT_STATUS_RUNNING,
    REPORT_STATUS_SUCCESS,
    REPORT_UPSTREAM_404,
    REQUEST_STATUS_CATEGORIZING,
    REQUEST_STATUS_FAILED,
    REQUEST_STATUS_PENDING,
    REQUEST_STATUS_READY,
    REQUEST_STATUS_RUNNING,
    RequestPaths,
    SYSTEM_CATEGORY_ORDER,
    SettingsState,
    TERMINAL_ANALYSIS_STATUSES,
    TERMINAL_REPORT_STATUSES,
    VehicleReportNeedsInput,
    utc_now,
)
from ._service_core import ServiceCoreMixin
from ._service_json import _build_report_snapshot_id, _mask_secret, _read_json, _write_json
from ._service_listing_helpers import (
    _date_range_defaults,
    _is_out_of_range_price_evaluation,
    _is_us_origin,
    _location_display,
    _normalize_lookup_date,
    _normalize_lookup_identifier,
    _param_display,
    _param_map,
    _price_evaluation_display,
    _price_fields,
    _report_lookup_options,
    build_categorized_payload,
    summarize_record,
)
from ._service_reports import ServiceReportMixin
from ._service_reports_lookup_runtime import ServiceReportLookupRuntimeMixin
from ._service_reports_runtime import ServiceReportRuntimeMixin
from ._service_request_run import ServiceRunMixin
from ._service_store import RequestStore, SettingsStore


class ParserAppService(
    ServiceRunMixin,
    ServiceAnalysisMixin,
    ServiceReportMixin,
    ServiceReportLookupRuntimeMixin,
    ServiceReportRuntimeMixin,
    ServiceCategoryMixin,
    ServiceCoreMixin,
):
    pass


__all__ = [
    "ANALYSIS_PROGRESS_CALLING_MODEL",
    "ANALYSIS_PROGRESS_COLLECTING_DATA",
    "ANALYSIS_STATUS_CANCELLED",
    "ANALYSIS_STATUS_CANCELLING",
    "ANALYSIS_STATUS_FAILED",
    "ANALYSIS_STATUS_IDLE",
    "ANALYSIS_STATUS_RUNNING",
    "ANALYSIS_STATUS_SUCCESS",
    "ASSIGNABLE_CATEGORY_ORDER",
    "CATEGORY_DATA_NOT_VERIFIED",
    "CATEGORY_FAVORITES",
    "CATEGORY_IMPORTED_FROM_US",
    "CATEGORY_PRICE_OUT_OF_RANGE",
    "CATEGORY_TO_BE_CHECKED",
    "CancellationRequested",
    "CUSTOM_CATEGORY_PREFIX",
    "DEFAULT_REPORT_LOOKUP_DAYS_BACK",
    "DEFAULT_REPORT_LOOKUP_DAYS_FORWARD",
    "OPENAI_REDFLAG_MODEL",
    "OPENAI_RESPONSES_URL",
    "ParserAppService",
    "VehicleHistoryClient",
    "REPORT_MISSING_FIRST_REGISTRATION",
    "REPORT_MISSING_REGISTRATION",
    "REPORT_MISSING_REGISTRATION_AND_DATE",
    "REPORT_PROGRESS_FETCHING_IDENTITY",
    "REPORT_PROGRESS_FETCHING_REPORT",
    "REPORT_STATUS_CANCELLED",
    "REPORT_STATUS_CANCELLING",
    "REPORT_STATUS_FAILED",
    "REPORT_STATUS_IDLE",
    "REPORT_STATUS_NEEDS_INPUT",
    "REPORT_STATUS_RUNNING",
    "REPORT_STATUS_SUCCESS",
    "REPORT_UPSTREAM_404",
    "REQUEST_STATUS_CATEGORIZING",
    "REQUEST_STATUS_FAILED",
    "REQUEST_STATUS_PENDING",
    "REQUEST_STATUS_READY",
    "REQUEST_STATUS_RUNNING",
    "RequestPaths",
    "RequestStore",
    "SettingsState",
    "SettingsStore",
    "SYSTEM_CATEGORY_ORDER",
    "TERMINAL_ANALYSIS_STATUSES",
    "TERMINAL_REPORT_STATUSES",
    "VehicleReportNeedsInput",
    "_build_report_snapshot_id",
    "_date_range_defaults",
    "_is_out_of_range_price_evaluation",
    "_is_us_origin",
    "_location_display",
    "_mask_secret",
    "_normalize_lookup_date",
    "_normalize_lookup_identifier",
    "_param_display",
    "_param_map",
    "_price_evaluation_display",
    "_price_fields",
    "_read_json",
    "_report_lookup_options",
    "_write_json",
    "build_categorized_payload",
    "default_red_flag_analyzer",
    "fetch_otomoto_listing_page_data",
    "fetch_otomoto_vehicle_identity",
    "summarize_record",
    "utc_now",
]
