import WarningAmberRoundedIcon from "@mui/icons-material/WarningAmberRounded";
import VerifiedRoundedIcon from "@mui/icons-material/VerifiedRounded";
import ChevronLeftRoundedIcon from "@mui/icons-material/ChevronLeftRounded";
import ChevronRightRoundedIcon from "@mui/icons-material/ChevronRightRounded";
import CloseRoundedIcon from "@mui/icons-material/CloseRounded";
import DownloadRoundedIcon from "@mui/icons-material/DownloadRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import OpenInNewRoundedIcon from "@mui/icons-material/OpenInNewRounded";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import RefreshRoundedIcon from "@mui/icons-material/RefreshRounded";
import FactCheckRoundedIcon from "@mui/icons-material/FactCheckRounded";
import StarRoundedIcon from "@mui/icons-material/StarRounded";
import LocalOfferOutlinedIcon from "@mui/icons-material/LocalOfferOutlined";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import CancelRoundedIcon from "@mui/icons-material/CancelRounded";

export const IconAlert = WarningAmberRoundedIcon;
export const IconCheckBadge = VerifiedRoundedIcon;
export const IconChevronLeft = ChevronLeftRoundedIcon;
export const IconChevronRight = ChevronRightRoundedIcon;
export const IconClose = CloseRoundedIcon;
export const IconDownload = DownloadRoundedIcon;
export const IconEdit = EditRoundedIcon;
export const IconExternal = OpenInNewRoundedIcon;
export const IconPlus = AddRoundedIcon;
export const IconRefresh = RefreshRoundedIcon;
export const IconReport = FactCheckRoundedIcon;
export const IconStar = StarRoundedIcon;
export const IconTag = LocalOfferOutlinedIcon;
export const IconTrash = DeleteOutlineRoundedIcon;
export const IconXBadge = CancelRoundedIcon;
